using ProseFlow.Core.Abstracts;

namespace ProseFlow.Core.Models;

/// <summary>
/// Represents a record of a past AI interaction.
/// </summary>
public class HistoryEntry : EntityBase
{
    /// <summary>
    /// The date and time when the interaction occurred.
    /// </summary>
    public DateTime Timestamp { get; set; }

    /// <summary>
    /// The name of the action that was executed.
    /// </summary>
    public required string ActionName { get; set; }

    /// <summary>
    /// The original input text provided by the user.
    /// </summary>
    public required string InputText { get; set; }

    /// <summary>
    /// The final output text generated by the AI.
    /// </summary>
    public required string OutputText { get; set; }

    /// <summary>
    /// The name of the AI provider that processed the request (e.g., "Cloud").
    /// </summary>
    public required string ProviderUsed { get; set; }
}