// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProseFlow.Infrastructure.Data;

#nullable disable

namespace ProseFlow.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250727223835_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("ProseFlow.Core.Models.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApplicationContext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExplainChanges")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instruction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("OpenInWindow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("ProseFlow.Core.Models.GeneralSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionMenuHotkey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LaunchAtLogin")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SmartPasteActionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmartPasteHotkey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GeneralSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActionMenuHotkey = "Ctrl+J",
                            LaunchAtLogin = false,
                            SmartPasteHotkey = "Ctrl+Shift+V",
                            Theme = "System"
                        });
                });

            modelBuilder.Entity("ProseFlow.Core.Models.HistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderUsed")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("History");
                });

            modelBuilder.Entity("ProseFlow.Core.Models.ProviderSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudApiKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("CloudTemperature")
                        .HasColumnType("REAL");

                    b.Property<string>("FallbackProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LocalCpuCores")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalModelPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PreferGpu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProviderSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseUrl = "https://api.openai.com/v1",
                            CloudApiKey = "",
                            CloudModel = "gpt-4o",
                            CloudTemperature = 0.7f,
                            FallbackProvider = "None",
                            LocalCpuCores = 4,
                            LocalModelPath = "",
                            PreferGpu = true,
                            PrimaryProvider = "Cloud"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
